import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Page from '../../components/Page'
import Button from '../../components/Button'
import ListUser from '../../components/ListUser'
import { useState } from 'react';
import { User } from '../../types/User'
import { SearchRes } from '../../types/SearchRes'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [isLoading,setIsLoading] = useState(false);
  const [cari,setCari] = useState("")
  const [result,setResult] = useState<SearchRes | null>(null)

  const onSearchSubmit=(e:React.FormEvent<HTMLFormElement>)=>{
    e.preventDefault();
    if(cari){
      setIsLoading(true)
      fetch(`https://api.github.com/search/users?q=${cari}&per_page=20`)
            .then(res=>res.json())
            .then(data=>{
              const user : User[] = data.items
              const searchRes:SearchRes={
                search:cari,
                users:user
              }
              setResult(searchRes)
            }).finally(()=>{
              setIsLoading(false)
            })
    }
  }

  return (
    <>
      <Head>
        <title>FE Test Muhammad Rakha Harisma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        <div className={styles.card}>
          <form className='flex place-self-center space-x-3' onSubmit={onSearchSubmit}>
            <Page value={cari} onChange={(e)=>setCari(e.target.value)} />
            <Button type='submit' isLoading={isLoading} />
          </form>
          {result && <ListUser result={result} />}
        </div>
      </main>
    </>
  )
}
